### ISSUE TITLE
wxFormBuilder has a tiny toolbar icons

### ISSUE THREAD

**Issue by ohyubun** [wxFormBuilder/wxFormBuilder#501] opened 2019-02-19 03:43 UTC
I am using wxFormBuilder  3.0 in Windows 10.
I got the following screen snapshoot.It The item icon is too small for me to select a right icon.

![image](https://user-images.githubusercontent.com/14212542/52988602-e8344d00-343a-11e9-8b4c-19f2c8b7cb76.png)

**Comment by jhasse** [comment] 2019-02-19 14:43
Duplicate of #295.

**Closed by jhasse** 2019-02-19 14:43 UTC
