### ISSUE TITLE
compiled on ubuntu 20.04 gives erros cannot find libs

### ISSUE THREAD

**Issue by cjdg** [wxFormBuilder/wxFormBuilder#627] opened 2020-07-27 05:29 UTC
Compiling on ubuntu 20.04 has errors that cannot populate database and libs are inacessible

**Comment by cjdg** [comment] 2020-07-27 05:32
had to move wxformbuilder from x86_64-linux-gnu folder

**Comment by sodevel** [comment] 2020-07-27 18:51
Duplicate of #524, possible solutions are listed there.

**Closed by sodevel** 2020-07-27 18:51 UTC
Labels: duplicate
