### ISSUE TITLE
error: ambiguous overload for operator[]

### ISSUE THREAD

**Issue by sinancetinkaya** [wxFormBuilder/wxFormBuilder#282] opened 2017-05-05 12:04 UTC
> $ make config=release
==== Building TiCPP (release) ====
ticpp.cpp
tinystr.cpp
tinyxml.cpp
tinyxmlerror.cpp
tinyxmlparser.cpp
Linking TiCPP
==== Building plugin-interface (release) ====
Creating obj/Release/plugin-interface
xrcconv.cpp
../../../sdk/plugin_interface/xrcconv.cpp: In function ‘wxString StringToXrcText(const wxString&)’:
../../../sdk/plugin_interface/xrcconv.cpp:41:17: error: ambiguous overload for  operator[]’ (operand types are ‘const wxString’ and ‘unsigned int’)
   wxChar c = str[i];
                 ^
../../../sdk/plugin_interface/xrcconv.cpp:41:17: note: candidate: operator[](const char*, long int) <built-in>
../../../sdk/plugin_interface/xrcconv.cpp:41:17: note: candidate: operator[](const wchar_t*, long int) <built-in>
In file included from /mingw32/include/wx-3.0/wx/memory.h:15:0,
                 from /mingw32/include/wx-3.0/wx/object.h:19,
                 from /mingw32/include/wx-3.0/wx/wx.h:15,
                 from ../../../sdk/plugin_interface/xrcconv.h:26,
                 from ../../../sdk/plugin_interface/xrcconv.cpp:26:
/mingw32/include/wx-3.0/wx/string.h:1544:15: note: candidate: wxUniChar wxString::operator[](int) const
     wxUniChar operator[](int n) const
               ^
/mingw32/include/wx-3.0/wx/string.h:1546:15: note: candidate: wxUniChar wxString::operator[](long int) const
     wxUniChar operator[](long n) const
               ^
/mingw32/include/wx-3.0/wx/string.h:1548:15: note: candidate: wxUniChar wxString::operator[](size_t) const
     wxUniChar operator[](size_t n) const
               ^
../../../sdk/plugin_interface/xrcconv.cpp: In function ‘wxString XrcTextToString(const wxString&)’:
../../../sdk/plugin_interface/xrcconv.cpp:77:17: error: ambiguous overload for  operator[]’ (operand types are ‘const wxString’ and ‘unsigned int’)
   wxChar c = str[i];
                 ^
../../../sdk/plugin_interface/xrcconv.cpp:77:17: note: candidate: operator[](const char*, long int) <built-in>
../../../sdk/plugin_interface/xrcconv.cpp:77:17: note: candidate: operator[](const wchar_t*, long int) <built-in>
In file included from /mingw32/include/wx-3.0/wx/memory.h:15:0,
                 from /mingw32/include/wx-3.0/wx/object.h:19,
                 from /mingw32/include/wx-3.0/wx/wx.h:15,
                 from ../../../sdk/plugin_interface/xrcconv.h:26,
                 from ../../../sdk/plugin_interface/xrcconv.cpp:26:
/mingw32/include/wx-3.0/wx/string.h:1544:15: note: candidate: wxUniChar wxString::operator[](int) const
     wxUniChar operator[](int n) const
               ^
/mingw32/include/wx-3.0/wx/string.h:1546:15: note: candidate: wxUniChar wxString::operator[](long int) const
     wxUniChar operator[](long n) const
               ^
/mingw32/include/wx-3.0/wx/string.h:1548:15: note: candidate: wxUniChar wxString::operator[](size_t) const
     wxUniChar operator[](size_t n) const
               ^
../../../sdk/plugin_interface/xrcconv.cpp:80:21: error: ambiguous overload for  operator[]’ (operand types are ‘const wxString’ and ‘unsigned int’)
    wxChar next = str[i+1];
                     ^
../../../sdk/plugin_interface/xrcconv.cpp:80:21: note: candidate: operator[](const char*, long int) <built-in>
../../../sdk/plugin_interface/xrcconv.cpp:80:21: note: candidate: operator[](const wchar_t*, long int) <built-in>
In file included from /mingw32/include/wx-3.0/wx/memory.h:15:0,
                 from /mingw32/include/wx-3.0/wx/object.h:19,
                 from /mingw32/include/wx-3.0/wx/wx.h:15,
                 from ../../../sdk/plugin_interface/xrcconv.h:26,
                 from ../../../sdk/plugin_interface/xrcconv.cpp:26:
/mingw32/include/wx-3.0/wx/string.h:1544:15: note: candidate: wxUniChar wxString::operator[](int) const
     wxUniChar operator[](int n) const
               ^
/mingw32/include/wx-3.0/wx/string.h:1546:15: note: candidate: wxUniChar wxString::operator[](long int) const
     wxUniChar operator[](long n) const
               ^
/mingw32/include/wx-3.0/wx/string.h:1548:15: note: candidate: wxUniChar wxString::operator[](size_t) const
     wxUniChar operator[](size_t n) const
               ^
../../../sdk/plugin_interface/xrcconv.cpp:99:36: error: ambiguous overload for  operator[]’ (operand types are ‘const wxString’ and ‘unsigned int’)
    if ( i < str.Length() - 1 && str[i+1] == wxChar( '_' ) )
                                    ^
../../../sdk/plugin_interface/xrcconv.cpp:99:36: note: candidate: operator[](const char*, long int) <built-in>
../../../sdk/plugin_interface/xrcconv.cpp:99:36: note: candidate: operator[](const wchar_t*, long int) <built-in>
In file included from /mingw32/include/wx-3.0/wx/memory.h:15:0,
                 from /mingw32/include/wx-3.0/wx/object.h:19,
                 from /mingw32/include/wx-3.0/wx/wx.h:15,
                 from ../../../sdk/plugin_interface/xrcconv.h:26,
                 from ../../../sdk/plugin_interface/xrcconv.cpp:26:
/mingw32/include/wx-3.0/wx/string.h:1544:15: note: candidate: wxUniChar wxString::operator[](int) const
     wxUniChar operator[](int n) const
               ^
/mingw32/include/wx-3.0/wx/string.h:1546:15: note: candidate: wxUniChar wxString::operator[](long int) const
     wxUniChar operator[](long n) const
               ^
/mingw32/include/wx-3.0/wx/string.h:1548:15: note: candidate: wxUniChar wxString::operator[](size_t) const
     wxUniChar operator[](size_t n) const
               ^
make[1]: *** [plugin-interface.make:131: obj/Release/plugin-interface/xrcconv.o] Error 1
make: *** [Makefile:21: plugin-interface] Error 2

OS: Windows 10 64 bit
Also the 
**"Install From Source
Windows (MSYS2)"** 
 is not working.
I had to install gcc using "pacman -S gcc"

**Comment by jhasse** [comment] 2017-06-13 07:20
> Also the
> "Install From Source
> Windows (MSYS2)"
> is not working.

Can you specify what exactly is not working?

**Comment by jhasse** [comment] 2018-06-23 08:09
Can you share some details on how to reproduce it?

**Comment by synchrowisdom** [comment] 2018-07-26 18:56
Hi, I'm having the same problem here. I followed the instructions from https://github.com/wxFormBuilder/wxFormBuilder but got the error at compile. Below is the followed steps:

pacman -S --needed mingw-w64-i686-wxWidgets git make mingw-w64-i686-binutils mingw-w64-i686-gcc mingw-w64-i686-boost
git clone --recursive --depth=1 https://github.com/wxFormBuilder/wxFormBuilder
cd wxFormBuilder
cmd.exe /C "create_build_files4.bat --wx-root=/mingw32/bin --force-wx-config --disable-mediactrl"
ln -s /mingw32/include/binutils/bfd.h /mingw32/include/bfd.h
ln -s /mingw32/include/binutils/symcat.h /mingw32/include/symcat.h
ln -s /mingw32/lib/binutils/libbfd.a /mingw32/lib/libbfd.a
ln -s /mingw32/lib/binutils/libiberty.a /mingw32/lib/libiberty.a
cd build/3.0/gmake
sed 's!\$(LDFLAGS) \$(RESOURCES) \$(ARCH) \$(LIBS)!\$(LIBS) \$(LDFLAGS) \$(RESOURCES) \$(ARCH)!g' *.make -i
sed 's!-lbfd!-lbfd -lz!g' *.make -i

$ make config=release
==== Building TiCPP (release) ====
ticpp.cpp
tinystr.cpp
tinyxml.cpp
tinyxmlerror.cpp
tinyxmlparser.cpp
Linking TiCPP
==== Building plugin-interface (release) ====
Creating obj/Release/plugin-interface
xrcconv.cpp
In file included from C:/msys64/mingw32/include/wx-3.0/wx/wx.h:14:0,
                 from ../../../sdk/plugin_interface/xrcconv.h:26,
                 from ../../../sdk/plugin_interface/xrcconv.cpp:26:
C:/msys64/mingw32/include/wx-3.0/wx/defs.h: In function 'wxUIntPtr wxPtrToUInt(c                                                                                                                                                                                               onst void*)':
C:/msys64/mingw32/include/wx-3.0/wx/defs.h:295:56: warning: cast from 'const voi                                                                                                                                                                                               d*' to 'wxUIntPtr {aka long unsigned int}' loses precision [-fpermissive]
 #define wx_reinterpret_cast(t, x) reinterpret_cast<t>(x)
                                                        ^
C:/msys64/mingw32/include/wx-3.0/wx/defs.h:1332:12: note: in expansion of macro                                                                                                                                                                                                'wx_reinterpret_cast'
     return wx_reinterpret_cast(wxUIntPtr, p);
            ^~~~~~~~~~~~~~~~~~~
../../../sdk/plugin_interface/xrcconv.cpp: In function 'wxString StringToXrcText                                                                                                                                                                                               (const wxString&)':
../../../sdk/plugin_interface/xrcconv.cpp:39:17: error: ambiguous overload for                                                                                                                                                                                                 operator[]' (operand types are 'const wxString' and 'unsigned int')
   wxChar c = str[i];
                 ^
../../../sdk/plugin_interface/xrcconv.cpp:39:17: note: candidate: operator[](con                                                                                                                                                                                               st char*, long long int) <built-in>
../../../sdk/plugin_interface/xrcconv.cpp:39:17: note: candidate: operator[](con                                                                                                                                                                                               st wchar_t*, long long int) <built-in>
In file included from C:/msys64/mingw32/include/wx-3.0/wx/memory.h:15:0,
                 from C:/msys64/mingw32/include/wx-3.0/wx/object.h:19,
                 from C:/msys64/mingw32/include/wx-3.0/wx/wx.h:15,
                 from ../../../sdk/plugin_interface/xrcconv.h:26,
                 from ../../../sdk/plugin_interface/xrcconv.cpp:26:
C:/msys64/mingw32/include/wx-3.0/wx/string.h:1544:15: note: candidate: wxUniChar                                                                                                                                                                                                wxString::operator[](int) const
     wxUniChar operator[](int n) const
               ^~~~~~~~
C:/msys64/mingw32/include/wx-3.0/wx/string.h:1546:15: note: candidate: wxUniChar                                                                                                                                                                                                wxString::operator[](long int) const
     wxUniChar operator[](long n) const
               ^~~~~~~~
C:/msys64/mingw32/include/wx-3.0/wx/string.h:1548:15: note: candidate: wxUniChar                                                                                                                                                                                                wxString::operator[](size_t) const
     wxUniChar operator[](size_t n) const
               ^~~~~~~~
../../../sdk/plugin_interface/xrcconv.cpp: In function 'wxString XrcTextToString                                                                                                                                                                                               (const wxString&)':
../../../sdk/plugin_interface/xrcconv.cpp:75:17: error: ambiguous overload for                                                                                                                                                                                                 operator[]' (operand types are 'const wxString' and 'unsigned int')
   wxChar c = str[i];
                 ^
../../../sdk/plugin_interface/xrcconv.cpp:75:17: note: candidate: operator[](con                                                                                                                                                                                               st char*, long long int) <built-in>
../../../sdk/plugin_interface/xrcconv.cpp:75:17: note: candidate: operator[](con                                                                                                                                                                                               st wchar_t*, long long int) <built-in>
In file included from C:/msys64/mingw32/include/wx-3.0/wx/memory.h:15:0,
                 from C:/msys64/mingw32/include/wx-3.0/wx/object.h:19,
                 from C:/msys64/mingw32/include/wx-3.0/wx/wx.h:15,
                 from ../../../sdk/plugin_interface/xrcconv.h:26,
                 from ../../../sdk/plugin_interface/xrcconv.cpp:26:
C:/msys64/mingw32/include/wx-3.0/wx/string.h:1544:15: note: candidate: wxUniChar                                                                                                                                                                                                wxString::operator[](int) const
     wxUniChar operator[](int n) const
               ^~~~~~~~
C:/msys64/mingw32/include/wx-3.0/wx/string.h:1546:15: note: candidate: wxUniChar                                                                                                                                                                                                wxString::operator[](long int) const
     wxUniChar operator[](long n) const
               ^~~~~~~~
C:/msys64/mingw32/include/wx-3.0/wx/string.h:1548:15: note: candidate: wxUniChar                                                                                                                                                                                                wxString::operator[](size_t) const
     wxUniChar operator[](size_t n) const
               ^~~~~~~~
../../../sdk/plugin_interface/xrcconv.cpp:78:21: error: ambiguous overload for                                                                                                                                                                                                 operator[]' (operand types are 'const wxString' and 'unsigned int')
    wxChar next = str[i+1];
                     ^
../../../sdk/plugin_interface/xrcconv.cpp:78:21: note: candidate: operator[](con                                                                                                                                                                                               st char*, long long int) <built-in>
../../../sdk/plugin_interface/xrcconv.cpp:78:21: note: candidate: operator[](con                                                                                                                                                                                               st wchar_t*, long long int) <built-in>
In file included from C:/msys64/mingw32/include/wx-3.0/wx/memory.h:15:0,
                 from C:/msys64/mingw32/include/wx-3.0/wx/object.h:19,
                 from C:/msys64/mingw32/include/wx-3.0/wx/wx.h:15,
                 from ../../../sdk/plugin_interface/xrcconv.h:26,
                 from ../../../sdk/plugin_interface/xrcconv.cpp:26:
C:/msys64/mingw32/include/wx-3.0/wx/string.h:1544:15: note: candidate: wxUniChar                                                                                                                                                                                                wxString::operator[](int) const
     wxUniChar operator[](int n) const
               ^~~~~~~~
C:/msys64/mingw32/include/wx-3.0/wx/string.h:1546:15: note: candidate: wxUniChar                                                                                                                                                                                                wxString::operator[](long int) const
     wxUniChar operator[](long n) const
               ^~~~~~~~
C:/msys64/mingw32/include/wx-3.0/wx/string.h:1548:15: note: candidate: wxUniChar                                                                                                                                                                                                wxString::operator[](size_t) const
     wxUniChar operator[](size_t n) const
               ^~~~~~~~
../../../sdk/plugin_interface/xrcconv.cpp:97:36: error: ambiguous overload for                                                                                                                                                                                                 operator[]' (operand types are 'const wxString' and 'unsigned int')
    if ( i < str.Length() - 1 && str[i+1] == wxChar( '_' ) )
                                    ^
../../../sdk/plugin_interface/xrcconv.cpp:97:36: note: candidate: operator[](con                                                                                                                                                                                               st char*, long long int) <built-in>
../../../sdk/plugin_interface/xrcconv.cpp:97:36: note: candidate: operator[](con                                                                                                                                                                                               st wchar_t*, long long int) <built-in>
In file included from C:/msys64/mingw32/include/wx-3.0/wx/memory.h:15:0,
                 from C:/msys64/mingw32/include/wx-3.0/wx/object.h:19,
                 from C:/msys64/mingw32/include/wx-3.0/wx/wx.h:15,
                 from ../../../sdk/plugin_interface/xrcconv.h:26,
                 from ../../../sdk/plugin_interface/xrcconv.cpp:26:
C:/msys64/mingw32/include/wx-3.0/wx/string.h:1544:15: note: candidate: wxUniChar                                                                                                                                                                                                wxString::operator[](int) const
     wxUniChar operator[](int n) const
               ^~~~~~~~
C:/msys64/mingw32/include/wx-3.0/wx/string.h:1546:15: note: candidate: wxUniChar                                                                                                                                                                                                wxString::operator[](long int) const
     wxUniChar operator[](long n) const
               ^~~~~~~~
C:/msys64/mingw32/include/wx-3.0/wx/string.h:1548:15: note: candidate: wxUniChar                                                                                                                                                                                                wxString::operator[](size_t) const
     wxUniChar operator[](size_t n) const
               ^~~~~~~~
make[1]: *** [plugin-interface.make:131: obj/Release/plugin-interface/xrcconv.o]                                                                                                                                                                                                Error 1
make: *** [Makefile:21: plugin-interface] Error 2

**Comment by jhasse** [comment] 2018-07-27 07:32
Have you run `pacman -Syu` as described here http://www.msys2.org/ ?

**Comment by synchrowisdom** [comment] 2018-07-27 16:15
I did and I have also checked and tried to compile on all 3 systems: MSYS2, Mingw-w64 32 bit and Mingw-w64 64 bit.

Here is the output I get from updating my system again, it looks like it is fully up-to-date:
$ pacman -Syu
:: Synchronising package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do

$ pacman -Su
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do


The error I've posted in my previous entry is when trying to compile from MYSY2 or Mingw 64 bit version. I'm getting a different error from the Mingw 32 bit version. Here is what the 32 bit version gives me:

$ make config=release
==== Building TiCPP (release) ====
==== Building plugin-interface (release) ====
==== Building additional-components-plugin (release) ====
Linking additional-components-plugin
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-min                                                                                                                                                                                               gw32/bin/ld.exe: obj/Release/additional-components-plugin/additional.o:additiona                                                                                                                                                                                               l.cpp:(.text$_ZNK5ticpp4Base24BuildDetailedErrorStringB5cxx11Ev[__ZNK5ticpp4Base                                                                                                                                                                                               24BuildDetailedErrorStringB5cxx11Ev]+0x16a): undefined reference to `TiXmlNode::                                                                                                                                                                                               GetDocument() const'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-min                                                                                                                                                                                               gw32/bin/ld.exe: obj/Release/additional-components-plugin/additional.o:additiona                                                                                                                                                                                               l.cpp:(.text$_ZN18HyperlinkComponent13ImportFromXrcEPN5ticpp7ElementE[__ZN18Hype                                                                                                                                                                                               rlinkComponent13ImportFromXrcEPN5ticpp7ElementE]+0x27e): undefined reference to                                                                                                                                                                                                `ticpp::Node::FirstChildElement(char const*, bool) const'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-min                                                                                                                                                                                               gw32/bin/ld.exe: obj/Release/additional-components-plugin/additional.o:additiona                                                                                                                                                                                               l.cpp:(.text$_ZN18HyperlinkComponent13ImportFromXrcEPN5ticpp7ElementE[__ZN18Hype                                                                                                                                                                                               rlinkComponent13ImportFromXrcEPN5ticpp7ElementE]+0x2c6): undefined reference to                                                                                                                                                                                                `ticpp::Element::GetTextImp(std::__cxx11::basic_string<char, std::char_traits<ch                                                                                                                                                                                               ar>, std::allocator<char> >*) const'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-min                                                                                                                                                                                               gw32/bin/ld.exe: obj/Release/additional-components-plugin/additional.o:additiona                                                                                                                                                                                               l.cpp:(.text$_ZN18HyperlinkComponent13ImportFromXrcEPN5ticpp7ElementE[__ZN18Hype                                                                                                                                                                                               rlinkComponent13ImportFromXrcEPN5ticpp7ElementE]+0x468): undefined reference to                                                                                                                                                                                                `ticpp::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<c                                                                                                                                                                                               har>, std::allocator<char> > const&)'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-min                                                                                                                                                                                               gw32/bin/ld.exe: obj/Release/additional-components-plugin/additional.o:additiona                                                                                                                                                                                               l.cpp:(.text$_ZN18HyperlinkComponent13ImportFromXrcEPN5ticpp7ElementE[__ZN18Hype                                                                                                                                                                                               rlinkComponent13ImportFromXrcEPN5ticpp7ElementE]+0x48b): undefined reference to                                                                                                                                                                                                `ticpp::Exception::~Exception()'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-min                                                                                                                                                                                               gw32/bin/ld.exe: ../../../sdk/lib/libwx_mswu_plugin-interface-3.0.a(xrcconv.o):x                                                                                                                                                                                               rcconv.cpp:(.text+0x606): undefined reference to `TiCppRCImp::IncRef()'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-min                                                                                                                                                                                               gw32/bin/ld.exe: ../../../sdk/lib/libwx_mswu_plugin-interface-3.0.a(xrcconv.o):x                                                                                                                                                                                               rcconv.cpp:(.text+0x66e): undefined reference to `ticpp::Node::Clone() const'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-min                                                                                                                                                                                               gw32/bin/ld.exe: ../../../sdk/lib/libwx_mswu_plugin-interface-3.0.a(xrcconv.o):x                                                                                                                                                                                               rcconv.cpp:(.text+0x682): undefined reference to `ticpp::Node::ToElement() const                                                                                                                                                                                               '
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-min                                                                                                                                                                                               gw32/bin/ld.exe: ../../../sdk/lib/libwx_mswu_plugin-interface-3.0.a(xrcconv.o):x                                                                                                                                                                                               rcconv.cpp:(.text+0x740): undefined reference to `ticpp::Node::FirstChildElement                                                                                                                                                                                               (char const*, bool) const'
...
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-min                                                                                                                                                                                               gw32/bin/ld.exe: ../../../sdk/lib/libwx_mswu_plugin-interface-3.0.a(xrcconv.o):x                                                                                                                                                                                               rcconv.cpp:(.text$_ZNK5ticpp4Base10FromStringIlEEvRKNSt7__cxx1112basic_stringIcS                                                                                                                                                                                               t11char_traitsIcESaIcEEEPT_[__ZNK5ticpp4Base10FromStringIlEEvRKNSt7__cxx1112basi                                                                                                                                                                                               c_stringIcSt11char_traitsIcESaIcEEEPT_]+0x3e3): undefined reference to `ticpp::E                                                                                                                                                                                               xception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std                                                                                                                                                                                               ::allocator<char> > const&)'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-min                                                                                                                                                                                               gw32/bin/ld.exe: ../../../sdk/lib/libwx_mswu_plugin-interface-3.0.a(xrcconv.o):x                                                                                                                                                                                               rcconv.cpp:(.text$_ZNK5ticpp4Base10FromStringIlEEvRKNSt7__cxx1112basic_stringIcS                                                                                                                                                                                               t11char_traitsIcESaIcEEEPT_[__ZNK5ticpp4Base10FromStringIlEEvRKNSt7__cxx1112basi                                                                                                                                                                                               c_stringIcSt11char_traitsIcESaIcEEEPT_]+0x404): undefined reference to `ticpp::E                                                                                                                                                                                               xception::~Exception()'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [additional-components-plugin.make:86: ../../../output/plugins/addi                                                                                                                                                                                               tional/libadditional.dll] Error 1
make: *** [Makefile:25: additional-components-plugin] Error 2

**Comment by jhasse** [comment] 2018-08-01 13:03
Could it be that you've generated the build files in the MinGW 64 bit shell and then only ran make in the 32 bit shell?

If so, please run

```
git clean -xfd
```

in the git checkout of wxFormBuilder (it will remove all untracked files!) and then continue with the commands from the README but only use the 32 bit shell at all times.

**Comment by synchrowisdom** [comment] 2018-08-01 19:00
Alright, I've tried your instructions and restarted the installation. This time is looks like it's working but I have a fatal error on diagnostics.h which seems to be missing or perhaps just the link to it is missing. Here is the output:

$ make config=release
==== Building TiCPP (release) ====
Creating ../../../sdk/lib
Creating obj/Release/TiCPP
ticpp.cpp
tinystr.cpp
tinyxml.cpp
tinyxmlerror.cpp
tinyxmlparser.cpp
Linking TiCPP
==== Building plugin-interface (release) ====
Creating obj/Release/plugin-interface
xrcconv.cpp
wizard.cpp
Linking plugin-interface
==== Building additional-components-plugin (release) ====
Creating obj/Release/additional-components-plugin
additional.cpp
Linking additional-components-plugin
==== Building common-components-plugin (release) ====
Creating obj/Release/common-components-plugin
common.cpp
Linking common-components-plugin
==== Building containers-components-plugin (release) ====
Creating obj/Release/containers-components-plugin
containers.cpp
Linking containers-components-plugin
==== Building forms-components-plugin (release) ====
Creating obj/Release/forms-components-plugin
forms.cpp
Linking forms-components-plugin
==== Building layout-components-plugin (release) ====
Creating obj/Release/layout-components-plugin
layout.cpp
Linking layout-components-plugin
==== Building wxFormBuilder (release) ====
Creating obj/Release/wxFormBuilder
maingui.cpp
codegen.cpp
codeparser.cpp
codewriter.cpp
cppcg.cpp
luacg.cpp
phpcg.cpp
pythoncg.cpp
xrccg.cpp
stack.cpp
In file included from ../../../src/dbg_stack_trace/stack.cpp:22:0:
C:/msys64/mingw32/include/bfd.h:44:10: fatal error: diagnostics.h: No such file or directory
 #include "diagnostics.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [wxFormBuilder.make:207: obj/Release/wxFormBuilder/stack.o] Error 1
make: *** [Makefile:45: wxFormBuilder] Error 2


=
===============================================
It looked to me like diagnostic.h is part of 'clang' so I tried installing this:
pacman -S mingw-w64-x86_64-clang mingw-w64-i686-clang

but no luck.

**Comment by jhasse** [comment] 2018-08-02 12:50
My `/mingw32/include/bfd.h` doesn't contain a line `#include "diagnostics.h"`.  Can you post the output of `pacman -Q --info mingw-w64-i686-binutils`? Is the file identical to `/mingw32/include/binutils/bfd.h`?

**Comment by synchrowisdom** [comment] 2018-08-02 13:01
Here is my output for pacman...

$ pacman -Q --info mingw-w64-i686-binutils
Name            : mingw-w64-i686-binutils
Version         : 2.31.1-1
Description     : A set of programs to assemble and manipulate binary and object
                  files (mingw-w64)
Architecture    : any
URL             : https://www.gnu.org/software/binutils/
Licenses        : GPL
Groups          : mingw-w64-i686-toolchain
Provides        : None
Depends On      : mingw-w64-i686-libiconv  mingw-w64-i686-zlib
Optional Deps   : None
Required By     : mingw-w64-i686-gcc
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 94.29 MiB
Packager        : Alexey Pavlov <alexpux@gmail.com>
Build Date      : 19 Jul 2018 04:06:53
Install Date    : 26 Jul 2018 14:12:06
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature


And about /mingw32/include/binutils/bfd.h, I can't say if they are identical but both files (the one in mingw32 and in mingw64) are containing the #include "diagnostics.h" on my installation.

**Comment by jhasse** [comment] 2018-08-03 12:48
Okay it seems that *my* package was out of date, sorry for that.

After running

```
ln -s /mingw32/include/binutils/diagnostics.h /mingw32/include/diagnostics.h
```

compilation with `make config=release` should work. I will add it to the README :)

**Comment by synchrowisdom** [comment] 2018-08-03 13:39
If you update your README, I would suggest to add a comment about closing MSYS2 after you have installed it as it will automatically launch the 64 version. Users should close MSYS2 and re-open it after t was installed and make sure to launch the 32 bit version.

I have added the missing symbolic link that you suggested and it seems like it's compiling correctly no. However, I'm having another error at the end, it looks like a wrong parameter is passed on to wx-config:

wxFormBuilder.rc
  *** Error: Unrecognised option: '--rcflags'
Use wx-config --help for information on command line options.

When looking at the available options, --rcflags doesn't seem to exist, could it be --cflags instead?
$ wx-config --help

 wx-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--release] [--version-full]
           [--list] [--selected-config] [--host=HOST] [--toolkit=TOOLKIT]
           [--universal[=yes|no]] [--unicode[=yes|no]] [--static[=yes|no]]
           [--debug[=yes|no]] [--version[=VERSION]] [--basename] [--cc] [--cxx]
           [--cppflags [base]] [--cxxflags [base]] [--cflags]
           [--rescomp] [--linkdeps] [--ld] [--utility=UTIL]
           [--libs [LIBS...]] [--optional-libs [LIBS...]]

    wx-config returns information about the wxWidgets libraries available on
  your system.  It may be used to retrieve the information required to build
  applications using these libraries using --cppflags, --cxxflags, --cflags,
  and --libs options. And you may query the properties of this configuration
  using --query-{host,toolkit,widgetset,chartype,debugtype,version,linkage}.
...

**Comment by jhasse** [comment] 2018-08-03 13:47
> However, I'm having another error at the end, it looks like a wrong parameter is passed on to

Yes, that's a long known issue, the error message can be ignored. IIRC the flag was only needed with older wx-config scripts or something like that.

Btw: Please pass code or terminal output inside 6 backticks on GitHub: https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks

**Comment by synchrowisdom** [comment] 2018-08-03 15:41
Awesome!  Many thanks for your help and for the tip about placing the code/console output into a code block ;)

**Closed** 2021-09-22 23:51 UTC
Labels: Windows
