### ISSUE TITLE
Unable to build on amd64 ubuntu 22.10

### ISSUE THREAD

**Issue by chmorgan** [wxFormBuilder/wxFormBuilder#768] opened 2023-02-04 14:17 UTC
Installed dependent packages via:

```
sudo apt install libwxgtk3.0-gtk3-dev libwxgtk-media3.0-gtk3-dev libboost-dev cmake make git
```

Ran the build command from the readme:

```
cmake -S . -B _build -G "Unix Makefiles" --install-prefix "$PWD/_install" -DCMAKE_BUILD_TYPE=Release -DWXFB_WXWIDGETS_ENABLE_30=ON
```

and even though I've got pretty much all wxwidgets packages installed the FindwxWidgets.cmake can't find wxWidgets....

```
cmorgan@ubuntu-qemu:~/projects/wxFormBuilder$ cmake -S . -B _build -G "Unix Makefiles" --install-prefix "$PWD/_install" -DCMAKE_BUILD_TYPE=Release -DWXFB_WXWIDGETS_ENABLE_30=ON
CMake Error at /usr/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES) (Required is at
  least version "3.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.24/Modules/FindwxWidgets.cmake:977 (find_package_handle_standard_args)
  CMakeLists.txt:140 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/cmorgan/projects/wxFormBuilder/_build/CMakeFiles/CMakeOutput.log".
```

Also tried with WXFB_WXWIDGETS_ENABLE_30=OFF, or dropping that argument, same error but slightly different versions.

I tried to debug for a half hour or so but haven't been able to figure out where the issue might be. It feels like CMakeLists.txt is asking for a rev of wxwidgets that isn't installed...

I'd gladly help with a PR if I knew where to start.

**Comment by sodevel** [comment] 2023-02-06 17:46
I think the error message means that it cannot find some of the requested library components. Here on GitHub only Ubuntu 22.04 is available and this one has only wxWidgets 3.0 available. The switch `WXFB_WXWIDGETS_ENABLE_30` lowers the version requirement of wxWidgets to 3.0, otherwise it looks for wxWidgets 3.1, hence you will get a version failure instead.

I checked the package contents of wxWidgets 3.0 for Ubuntu 22.10 and they look the same like for Ubuntu 22.04, so i don't know what could be missing. However, on your distro wxWidgets 3.2 is available, you should install that version instead and use CMake without that switch, maybe that fixes your issue.

Otherwise, some CMake `find_package()` debugging is necessary, this might take some time, i currently don't have an Ubuntu 22.10 box setup.

**Comment by sodevel** [comment] 2023-02-09 18:58
I have just build wxFB for Ubuntu 22.10 using sbuild and the build succeeded without error, so i cannot reproduce your error. If reinstalling the packages or using wxWidgets 3.2 does not help you, you could run CMake with additional debug output enabled. If the output doesn't help you, you could post it here and i can take a look.

Add the following switch to the cmake configure call above: `--debug-find-pkg=wxWidgets`
If that still doesn't give a clue, add the following switches as well: `--trace-expand --trace-source=FindwxWidgets.cmake`

**Comment by sodevel** [comment] 2023-06-23 19:17
Closing this because of no feedback, issue cannot be reproduced.

**Closed by sodevel** 2023-06-23 19:17 UTC
