### ISSUE TITLE
Combobox display problem

### ISSUE THREAD

**Issue by dcapeletti** [wxFormBuilder/wxFormBuilder#394] opened 2018-06-02 10:18 UTC
As you can see in the image, there seems to be a text box below a combobox. The drop-down menu of the combobox is not located at the end.
I am using wxformbuilder V3.6.2 on Debian 9 with gnome 3.22.2. Thank you for your help.

![imagen](https://user-images.githubusercontent.com/5890886/40873290-f4e12ada-6633-11e8-8fbc-333e6fefcd08.png)

**Comment by jhasse** [comment] 2018-09-12 09:13
I think this is a Gtk+ or wxWidgets bug which has been fixed in newer version. I can't reproduce this anymore with wxWidgets 3.0.4 and Gtk+ 3.22.30.

**Closed by jhasse** 2018-09-12 09:13 UTC
Labels: Linux, bug
