### ISSUE TITLE
wxStaticText incorrect display when used with wxChoice from wxScrolledWindow. 

### ISSUE THREAD

**Issue by Kvaz1r** [wxFormBuilder/wxFormBuilder#536] opened 2019-08-18 07:47 UTC
Screen:
![s1](https://user-images.githubusercontent.com/17313967/63221695-5f0d9100-c1a5-11e9-9d7b-e2ea29e9cff0.jpg)

Could be related to #318 and #317

**Comment by sodevel** [comment] 2019-08-19 18:23
And here i see that i don't see the wxStaticText label? I cannot reproduce this, but i remember there have been issues that drawing these selection overlays erased their content. This was caused in part by wxWidgets and required a newer version to fix this. What wxWidgets version are you using?

About these referenced issues, i think both are caused by an infinite recursion of events that got fixed in the past, these issues should be resolved by now.

There are still problems with these selection overlays especially together with scrolled windows, i tried to fix them in the past but didn't find a good solution.

**Comment by Kvaz1r** [comment] 2019-08-19 19:02
> And here i see that i don't see the wxStaticText label? This was caused in part by wxWidgets and required a newer version to fix this. What wxWidgets version are you using?

Yes. I use default one from msys2 so it's 3.0.4

> About these referenced issues, i think both are caused by an infinite recursion of events that got fixed in the past, these issues should be resolved by now.

Unfortunately I still can reproduce both of them.

**Comment by sodevel** [comment] 2019-08-19 19:24
I am using wxWidgets/wxWidgets@acef902ea60c5be41035c899976306e69f668d20 and cannot reproduce any of them. I think it doesn't matter that im using MSVC instead of GCC, i am still building on Windows.

Maybe you can update your wxWidgets to see if these issues are gone for you as well then.

**Comment by Kvaz1r** [comment] 2019-08-19 21:31
Well, yes, I probably can, but it's not principal so let's wait for stable release it should be appear somewhen.

**Comment by sodevel** [comment] 2019-09-11 00:12
This is a side effect of the infinite paint events defect which got fixed by https://github.com/wxWidgets/wxWidgets/pull/389. This is a wxWidgets issue and is fixed since wxWidgets 3.1.1. I don't see a solution how this can be worked around so im closing this for now.

**Closed by sodevel** 2019-09-11 00:12 UTC
Labels: wontfix
