### ISSUE TITLE
not compile with wxWidgets version 3.2 

### ISSUE THREAD

**Issue by KostinPavel** [wxFormBuilder/wxFormBuilder#746] opened 2022-07-22 05:36 UTC
run build()...
The Meson build system
Version: 0.62.1
Source dir: /var/tmp/pamac-build-pavel/wxformbuilder/src/wxFormBuilder-3.10.1
Build dir: /var/tmp/pamac-build-pavel/wxformbuilder/src/wxFormBuilder-3.10.1/_build
Build type: native build
Project name: wxformbuilder
Project version: undefined
C++ compiler for the host machine: c++ (gcc 12.1.0 "c++ (GCC) 12.1.0")
C++ linker for the host machine: c++ ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C++ supports arguments -Wall: YES 
Compiler for C++ supports arguments -Wextra: YES 
Compiler for C++ supports arguments -Winit-self: YES 
Compiler for C++ supports arguments -Wimplicit-fallthrough: YES 
Compiler for C++ supports arguments -Wpedantic: YES 
Compiler for C++ supports arguments -Wdelete-non-virtual-dtor: YES 
Compiler for C++ supports arguments -Wlogical-op: YES 
Compiler for C++ supports arguments -Wduplicated-cond: YES 
Compiler for C++ supports arguments -Wduplicated-branches: YES 
Compiler for C++ supports arguments -Wno-overloaded-virtual: YES 
Compiler for C++ supports arguments -Wtautological-compare: YES 
Compiler for C++ supports arguments -Wextra-semi: YES 
Compiler for C++ supports arguments -Wno-inconsistent-missing-override: NO 
Compiler for C++ supports arguments -Wno-ignored-qualifiers: YES 
Compiler for C++ supports arguments -Wno-unused-parameter: YES 
Compiler for C++ supports arguments -Wno-cast-function-type: YES 
meson.build:21: WARNING: Consider using the built-in warning_level option instead of using "-Wall".
meson.build:21: WARNING: Consider using the built-in warning_level option instead of using "-Wextra".
wx-config found: NO need ['>=3.0.3']
Run-time dependency WxWidgets found: NO (tried config-tool)

meson.build:30:0: ERROR: Dependency "wxwidgets" not found, tried config-tool

**Comment by sodevel** [comment] 2022-07-22 13:57
The Meson build system was removed from wxFB quite some time ago, CMake is the only build system now. I don't know how you are building wxFB with Meson nor am i familiar with Meson, i can't help you here.

**Comment by branalba** [comment] 2022-08-24 23:33
Just to help give this issue some closure, this error was caused by specifically the AUR package for wxformbuilder, [here](https://aur.archlinux.org/packages/wxformbuilder). Up until recently it was still using meson to compile, but it has since switched to CMake once a wxWidgets packaging change broke the build process.

I'm not the maintainer, but as a user of that package I was affected by the breakage. Hope this clears it up and the issue can be closed

**Comment by sodevel** [comment] 2022-09-02 20:38
Thanks for the info, since there was no more feedback from the OP, im closing this.

**Closed by sodevel** 2022-09-02 20:38 UTC

**Comment by KostinPavel** [comment] 2022-09-03 07:32
Good job. Thanks!
