### ISSUE TITLE
lib dir location

### ISSUE THREAD

**Issue by ziuq** [wxFormBuilder/wxFormBuilder#575] opened 2019-12-16 02:29 UTC
On Debian 10 and following the Ubuntu notes in the README.md,
wxFB  fails because `_install/lib/wxformbuilder/libforms.so`
should be 
`_install/lib/x86_64-linux-gnu/wxformbuilder/libforms.so`.
Thanks.

**Comment by jmoraleda** [comment] 2020-04-21 22:28
This is a duplicate of #524

**Closed** 2020-04-22 20:01 UTC
Labels: duplicate
