### ISSUE TITLE
"There is no tree item associated with this object." when using drag & drop in Object Tree

### ISSUE THREAD

**Issue by TomasRiker** [wxFormBuilder/wxFormBuilder#284] opened 2017-05-17 06:32 UTC
I'm working with release version 3.6.0. The error can be reproduced like this:

1. Create a frame and three nested box sizers.
![1](https://cloud.githubusercontent.com/assets/295205/26141209/f5f55c28-3ada-11e7-948f-58c6274ed3d4.png)
2. In the Object Tree window, drag the third (inner) box sizer and drop it onto the first (outer) box sizer.
![2](https://cloud.githubusercontent.com/assets/295205/26141225/0bdc302a-3adb-11e7-8335-29cee6e92ebe.png)
3. The error message "There is no tree item associated with this object." appears.
![3](https://cloud.githubusercontent.com/assets/295205/26141227/12c8f21a-3adb-11e7-99df-2d5b08b59a49.png)
4. In the Object Tree, the third box sizer has now disappeared.
![4](https://cloud.githubusercontent.com/assets/295205/26141244/2c41184e-3adb-11e7-986f-4aef0391c148.png)

It can also be reproduced more easily by just creating one frame and one box sizer inside, then dragging and dropping that box sizer onto the frame (of which it is already a child). It leads to the same behavior.

**Comment by jhasse** [comment] 2017-05-17 06:50
I think this is a duplicate of #259. We really need to release 3.6.1 with the fix included ...

**Closed by jhasse** 2017-05-17 06:50 UTC

**Comment by TomasRiker** [comment] 2017-05-17 06:51
Sorry for the duplicate. I searched for the error message, but found nothing.

**Comment by jhasse** [comment] 2017-05-17 07:28
Don't worry. I'm sorry that the bugfix hasn't been released already ;)

Btw: Can you try the master build to see if it works for you? https://ci.appveyor.com/api/projects/jhasse/wxformbuilder-461d5/artifacts/wxFormBuilder_win32.zip?branch=master

**Comment by TomasRiker** [comment] 2017-05-17 10:41
Works perfectly!
