### ISSUE TITLE
wxFormBuilder stop rendering after changing something in Properties Window on OS X

### ISSUE THREAD

**Issue by gamelaster** [wxFormBuilder/wxFormBuilder#348] opened 2018-01-22 11:05 UTC
I wanted to click EXPAND on element, but after that, the whole application absolutely stop rendering, whatever I click, the application doesn't change.

![GIF](http://g.recordit.co/klbyUQZNVY.gif)

macOS Serria 10.12, wxFormBuilder 3.6.1 (with fixes to make it running)

**Comment by jhasse** [comment] 2018-01-22 11:06
> with fixes to make it running

Which fixes?

**Comment by gamelaster** [comment] 2018-01-22 11:07
https://github.com/wxFormBuilder/wxFormBuilder/issues/340#issuecomment-354300996
and
https://github.com/wxFormBuilder/wxFormBuilder/issues/340#issuecomment-354303253

**Comment by nohal** [comment] 2018-01-25 02:31
This odd behaviour is not new, present even in 3.5 RC1 I still have here - Usually after changing a textual property of a "any" widget in a project that is not totally trivial, the GUI gets mostly unresponsive. I always get to it, but usually not as fast as @gamelaster (What he shows is 100% reproducible here).

**Comment by jhasse** [comment] 2018-02-06 12:20
Thanks to @nohal this should now be fixed when installing wxWidgets via `brew install wxmac --HEAD`.

Should we update Travis CI or wait for the release of 3.1.1 or even 3.2?

**Comment by nohal** [comment] 2018-02-06 12:27
I would probably wait for wx 3.1.1 release and then switched travis to use `brew install wxmac --devel` as soon as it means 3.1.1 - should be really soon now.
WX 3.2 can be anything from months to years away and I wouldn't wait for it, at least on macOS where the current wx code is really a big step forward from 3.0.

Also note that all my testing of wxFB built against wx3.1.1-rc was limited to 2 minutes after the initial "Wow, it works..."

**Comment by jhasse** [comment] 2018-02-06 12:35
Okay :) Btw: we're already using wxWidgets 3.1 for the Linux build. And due to #295 wxWidgets 3.2 can't come fast enough for Windows, too. It's a real pity this is taking so long.

I'll close this issue for now.

**Closed by jhasse** 2018-02-06 12:35 UTC
Labels: bug, macOS
