### ISSUE TITLE
Unwanted declaration generated for CustomControls although declaration field is left empty

### ISSUE THREAD

**Issue by robekras** [wxFormBuilder/wxFormBuilder#554] opened 2019-10-17 13:23 UTC
I use some CustomControls where the first one has the following declaration:
` GridMinMax*       m_apGrid[4][5];`

For all other CustomControls the 'declaration' field is left empty, and also the 'class' field is left empty.
The 'name' field contains e.g. a `m_apGrid[1][1]`, as it is a member of the array m_apGrid.
wxFB now creates an automatic declaration with the class, asterisk and the declaration which results in:
`* m_apGrid[1][1];`

This worked in older Versions (maybe <= 3.4.x).

I attached the zipped BugExample.tbp 

[BugExample.zip](https://github.com/wxFormBuilder/wxFormBuilder/files/3739464/BugExample.zip)

**Comment by JacoboSpain** [comment] 2019-10-17 20:53
I use version 3.9.0 and the assignments I think are correct.

With your file:
.h:

![imagen](https://user-images.githubusercontent.com/51421291/67046246-2f8ced80-f130-11e9-9463-c6240f66676a.png)


.cpp:

![imagen](https://user-images.githubusercontent.com/51421291/67046513-a629eb00-f130-11e9-982b-182d04636087.png)

**Comment by robekras** [comment] 2019-10-18 05:19
I use wxFB 3.9.0 on Windows 10
Your include file looks different to mine:

The assignment for the very first CustomControl m_apGrid[1][0] is correct.
But for all other CustomControls (m_apGrid[1][1], m_apGrid[1][2]....) it is not.

![wxFB](https://user-images.githubusercontent.com/10207990/67067692-91247a80-f177-11e9-884b-f5ed53dec979.png)

**Comment by sodevel** [comment] 2019-10-18 16:33
Now that is quite an interesting way to get arrays into wxFB.

You must have been using a version before 3.6.1, because since then, if no declaration or construction is present, a default one gets used. This feature creates these declarations altough your definition of these are empty and breaks your arrays.

But you don't need to (mis)-use the CustomControl anymore to get arrays, the current master version supports multi-dimensional arrays for everything. JacoboSpain seems to be using that version and hence cannot reproduce your issue. You don't seem to be using windows so i'm afraid you need to compile wxFB yourself (unless Travis CI does save the artifacts, which i don't know, and your machine is compatible).

With that version you don't have to specify the declaration at all, just make sure you use the correct class (it is specified as wxGrid but the construction creates a GridMinMax) and the declaration gets generated automatically. If the sole purpose for using the CustomControl was to get arrays and GridMinMax construction is identical to wxGrid you can simply use a wxGrid with the proper subclass and your arrays work out-of-the-box.

**Comment by sodevel** [comment] 2020-05-04 16:29
Closing this because this is intended behavior.

**Closed by sodevel** 2020-05-04 16:29 UTC
