### ISSUE TITLE
Any news regarding wxFormBuilder not being high dpi aware

### ISSUE THREAD

**Issue by Jdreioe** [wxFormBuilder/wxFormBuilder#555] opened 2019-11-05 08:41 UTC
Hi, I know this is a dublicate of #295, but it's been over 2 years now. 
Any news?
Also, if not, is there an alternative GUI-based form builder for python?

**Comment by sodevel** [comment] 2019-11-07 18:38
Please don't open another issue if there is already another open issue about the same topic. You even found that one yourself, just post in that one.

Because of limited time and more serious pending issues that need to be addressed and the existence of a workaround (at least on Windows, don't know if there is one for Linux/MacOS) i won't work on that in the near feature. But of course i will happily apply a PR that does address this issue.

**Comment by sodevel** [comment] 2019-11-07 18:39
Duplicate of #295

**Closed by sodevel** 2019-11-07 18:39 UTC
Labels: duplicate
