### ISSUE TITLE
Toolbar added to main Frame shows purple square only.

### ISSUE THREAD

**Issue by turotulco** [wxFormBuilder/wxFormBuilder#571] opened 2019-12-03 17:16 UTC
I've added an AUI Toolbar directly to the main frame, as suggested, but it only shows up as a small purple square at runtime. It shows up perfectly, with all of it's components in the Designer. At runtime... it hides. I've experimented with all of the object properties settings, and searcehed Google for days now. All of the tutorials and questions ask seem to be for much simpler problems. I know it' must be something I am doing wrong that I am not aware of, but I've run out of ideas.

**Comment by Kvaz1r** [comment] 2019-12-03 18:44
How to reproduce the behaviour? Which version wxFB and wxWidgets and under which OS do you use?

**Comment by sodevel** [comment] 2020-05-04 16:28
Closing this because of no user response.

**Closed by sodevel** 2020-05-04 16:28 UTC
