### ISSUE TITLE
App completely crashes on macOS

### ISSUE THREAD

**Issue by taniotanio7** [wxFormBuilder/wxFormBuilder#340] opened 2017-12-24 19:17 UTC
# How to reproduce the crash
- I have tried using the precompiled .zip from release v3.6.1 - app opens and immediately shuts down.
- I have tried to build wxFormBuilder myself following instructions in README.md - app crashes with following crash log: https://gist.github.com/taniotanio7/d6b611619a2478f5cf619a77d8b3291f
- Finally... I have tried to use solution mentioned in #313 (building with debug enabled) - same results as if using precompiled version

# The workaround
Currently, the only solution to make the app work was to use the old version 3.5.01 hosted on [SourceForge](https://sourceforge.net/projects/wxformbuilder/)

**Comment by Hurricane31337** [comment] 2017-12-26 23:03
I experienced the same problem on macOS 10.11.6 El Capitan.

**Comment by nohal** [comment] 2017-12-28 14:57
The problem is the mixup of the wxWidgets dylibs in the application bundle - there are two versions of several libraries included - one named using 3.0 and one using 3.0.0.3.0. macOS does not like this combination and before the crash complains with stuff like
```
objc[70777]: Class wxNSAppController is implemented in both /Applications/wxFormBuilder 2.app/Contents/libs/libwx_osx_cocoau_core-3.0.0.3.0.dylib (0x10fd384f0) and /Applications/wxFormBuilder.app/Contents/libs/libwx_osx_cocoau_core-3.0.dylib (0x10f51d4f0). One of the two will be used. Which one is undefined.
```
Until a fixed bundle is released, the current one can be fixed with
```
cd /Applications/wxFormBuilder.app/Contents/libs
rm -f libwx_baseu-3.0.0.3.0.dylib libwx_baseu_xml-3.0.0.3.0.dylib libwx_osx_cocoau_adv-3.0.0.3.0.dylib libwx_osx_cocoau_core-3.0.0.3.0.dylib libwx_osx_cocoau_html-3.0.0.3.0.dylib
ln -s libwx_baseu-3.0.dylib libwx_baseu-3.0.0.3.0.dylib
ln -s libwx_baseu_xml-3.0.dylib libwx_baseu_xml-3.0.0.3.0.dylib
ln -s libwx_osx_cocoau_adv-3.0.dylib libwx_osx_cocoau_adv-3.0.0.3.0.dylib
ln -s libwx_osx_cocoau_core-3.0.dylib libwx_osx_cocoau_core-3.0.0.3.0.dylib
ln -s libwx_osx_cocoau_html-3.0.dylib libwx_osx_cocoau_html-3.0.0.3.0.dylib
```
That makes the application start with the following runtime error displayed:
```
Error loading library /Applications/wxFormBuilder.app/Contents/PlugIns/libforms.dylib dlopen(/Applications/wxFormBuilder.app/Contents/PlugIns/libforms.dylib, 1): Library not loaded: /usr/local/opt/wxmac/lib/libwx_osx_cocoau_richtext-3.0.dylib
  Referenced from: /Applications/wxFormBuilder.app/Contents/PlugIns/libforms.dylib
  Reason: image not found <database.cpp@1405>
```
,but as the `Forms` tab is now missing, there is not much you can do with it anyway. I did not look further into this one.

**Comment by nohal** [comment] 2017-12-28 15:12
Couldn't resist - The reason for libforms.dylib not loading is clear - the paths to the wx libraries are not fixed for the bundle during packaging and point to the local paths on the build machine like
```
	/usr/local/opt/wxmac/lib/libwx_osx_cocoau_richtext-3.0.dylib (compatibility version 4.0.0, current version 4.0.0)
```
while they should look like
```
	@executable_path/../libs/libwx_osx_cocoau_richtext-3.0.dylib (compatibility version 4.0.0, current version 4.0.0)
```
which is the case with the other dylibs in `wxFormBuilder.app/Contents/PlugIns/`

To fix this in the installed application:
```
cd /Applications/wxFormBuilder.app/Contents/PlugIns/
DYLIBS=$(otool -L libforms.dylib | grep "/opt" | awk -F' ' '{ print $1 }')
for dylib in $DYLIBS; do install_name_tool -change $dylib @executable_path/../libs/$(basename $dylib) libforms.dylib; done;
```

And you have what seems to be an usable wxFormBuilder 3.6.1

**Comment by ph0rn** [comment] 2017-12-28 21:01
After those changes, I'm not able to add any components to forms. I get this error

> Impossible to create the object. Did you forget to add a sizer/parent object or turn on/off an AUI management?

**Comment by nohal** [comment] 2017-12-28 21:07
Are you really sure you created the form and added at least one sizer to it before trying to add any components to it? FWIW, I am not able to reproduce and even older versions produced exactly the same message on this user error.

**Comment by ph0rn** [comment] 2017-12-28 21:09
@nohal deleted my comment just as yours came in :P. Yep it was my mistake. All good here.
Thanks

**Closed** 2018-01-10 18:27 UTC
