### ISSUE TITLE
The `expanded` attribute of `object` tags in .fbp adds too much noise to diffs

### ISSUE THREAD

**Issue by Poddster** [wxFormBuilder/wxFormBuilder#382] opened 2018-04-19 08:58 UTC
Currently the `.fbp` file format has an `expanded` attribute on it's `object` tags. wxFormBuilder stores the current expanded/collapsed state of the object tree's branches using this format.

This means that opened up a .fbp file and changing the view of the tree by expanding and collapsing branches results in lots of values being flipped between 1 and 0 in the file.

I find this feature quite annoying if the .fbp file is under source control, as it means I get lots of diffs like:

    -                                        <object class="sizeritem" expanded="0">
    +                                        <object class="sizeritem" expanded="1">

Would it be possible to add an option to wxFormBuilder that causes it to **always** write out objects as `expanded="0"`, no matter what the visual state of the tree in the tool is? This way I can freely change the state of the tree in the GUI without touching the file on disk.

(An alternative would be to have a new version of the file format that doesn't track this information, but I imagine some people find it useful, hence it's inclusion).

**Comment by jhasse** [comment] 2018-04-19 10:57
I think there was some discussion about this in another issue, can't find it though.

In my opinion these settings shouldn't be part of the fbp file at all, but should rather be saved on the local machine.

**Comment by acolomb** [comment] 2018-07-10 20:08
Duplicate of #47.

**Comment by jhasse** [comment] 2018-07-10 20:13
Thanks!

**Closed** 2018-07-10 20:13 UTC
Labels: enhancement
